### ISSUE TITLE
Manual conversion should get rid of old SGML tool dependencies

### ISSUE THREAD

**Issue by glaubitz** [mattst88/aboot#1]
In Debian, ```aboot``` is currently threatened to be removed as it build-depends on old SGML tools:

> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832491
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=949711

Can we modify the doc generation system so it uses newer tools for creating the manpages? I'm not an SGML expert, so I'm not sure what to use (```docbook-utils``` maybe?) but I'm willing to help convert the SGML files by hand to something modern, if necessary.

**Comment by glaubitz** [comment]
I did some research and we could just use ```docbook2man``` and ```docbook2html``` from the ```docbook-utils``` package.

**Comment by tofurky** [comment]
hi @glaubitz , does https://github.com/tofurky/aboot/commit/3a0eb2db7ac7637e7743dc2e2f2f1f1192b23604 look OK?
of course the debian package would need to be adjusted to require opensp for build. it already has docbook-utils.
the re-generated man pages look fine to me.

**Comment by glaubitz** [comment]
No, I rather don't want to use ```opensp``` as it's likely to be removed as well. Also, this is missing the HTML documentation.

I will create a patch later today, I'm currently at FOSDEM.
